apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: trinobackends.trino.example.com
spec:
  group: trino.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                proxyTo:
                  type: string
                active:
                  type: boolean
                routingGroup:
                  type: string
                externalUrl:
                  type: string
              required:
                - name
                - proxyTo
                - active
                - routingGroup
  scope: Namespaced
  names:
    plural: trinobackends
    singular: trinobackend
    kind: TrinoBackend
    shortNames:
      - tb
